[[redirects]]
from = "/code-of-conduct"
to = "/open-source/code-of-conduct"

[[redirects]]
from = "/docs/Decentralized%20Web%20Platform%20-%20Public.pdf"
to = "/files/Decentralized-Web-Platform.pdf"

[[redirects]]
from = "/build/troubleshooting-guide"
to = "/decentralized-web-nodes/troubleshooting/common-errors"

[[redirects]]
from = "/troubleshooting-guide"
to = "/decentralized-web-nodes/troubleshooting/common-errors"

[[redirects]]
from = "/build/frameworks/next"
to = "/decentralized-web-nodes/troubleshooting/next"

[[redirects]]
from = "/build/frameworks/vue"
to = "/decentralized-web-nodes/troubleshooting/vue"

[[redirects]]
from = "/troubleshooting/*"
to = "/decentralized-web-nodes/troubleshooting/:splat"
status = 301

[[redirects]]
from = "/build/*"
to = "/:splat"
status = 301
force = true

[[redirects]]
from = "/learn/decentralized-identifiers"
to = "/decentralized-identifiers/what-are-dids"

[[redirects]]
from = "/learn/decentralized-web-nodes"
to = "/decentralized-web-nodes/what-are-dwns"

[[redirects]]
from = "/learn/verifiable-credentials"
to = "/verifiable-credentials/what-are-vcs"

[[redirects]]
from = "/learn/did_documents"
to = "/decentralized-identifiers/did_documentss"

[[redirects]]
from = "/learn/agents"
to = "/decentralized-web-nodes/agents"

[[redirects]]
from = "/learn/protocols"
to = "/decentralized-web-nodes/what-are-protocols"

[[redirects]]
from = "/learn/sync"
to = "/decentralized-web-nodes/sync"

[[redirects]]
from = "/decentralized-web-nodes/protocols"
to = "/decentralized-web-nodes/what-are-protocols"
